--- # this is an yaml for installion of httpd
- hosts: centos
  become: yes
  tasks:
  - name: install httpd on centos
    yum:
      name: httpd
      state: latest
  - name: create file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add content to index
    lineinfile:
      name: "Hello Ansible - I am welcome to you"
      path: /var/www/html/index.html 
  - name: starting service
    service:
      name: httpd
      state: started
